### ISSUE TITLE
bug: spark/io.py uses private _jsc.hadoopConfiguration() — breaks Spark Connect and may silently fail on cached S3A FileSystem

### ISSUE THREAD

**Issue by sallycr** [michelangelo-ai/michelangelo#1286]
**Describe the bug**

`_ensure_s3a_config()` in `python/michelangelo/uniflow/plugins/spark/io.py` (line 45) injects S3A credentials into a running Spark session via the undocumented Py4J bridge `spark.sparkContext._jsc.hadoopConfiguration()`. This is not part of the public PySpark API and causes two distinct problems:

1. **Silent credential miss on cached FileSystem.** Spark (via Hadoop) caches `FileSystem` instances per URI scheme in `FileSystem.CACHE` inside the JVM. If any code path in `SparkTask.pre_run` (e.g. Hive metastore init, event-log setup) opens an `s3a://` path before the task body's first I/O call, the `FileSystem` object is instantiated with empty credentials. The subsequent `hadoopConfiguration().set(...)` calls mutate the live `Configuration` but the already-cached `FileSystem` instance is not re-initialized, so S3A reads/writes silently fail with `AccessDenied` or `NoCredentialsError`.

2. **AttributeError on Spark Connect.** Spark Connect (the default in Spark 4.x and available in 3.5+) removes the embedded JVM from the client side. `spark.sparkContext._jsc` does not exist in that mode; any I/O call raises `AttributeError: 'SparkContext' object has no attribute '_jsc'` with no useful message to the user.

**To Reproduce**

```python
# 1. Start a SparkTask that enables Hive support (the current pre_run)
# 2. Ensure AWS_ACCESS_KEY_ID is set in the environment
# 3. Call preprocess() — SparkTask.pre_run runs, Hive metastore touches s3a://
# 4. Inside the task, load_spark_dataframe() calls _ensure_s3a_config()
# 5. hadoopConfiguration().set(...) succeeds, but the cached S3AFileSystem
#    was already instantiated without credentials → AccessDeniedException
```

Alternatively, run against a Spark Connect server:
```python
spark = SparkSession.builder.remote("sc://localhost").getOrCreate()
# Any SparkIO read/write call will raise:
# AttributeError: 'SparkContext' object has no attribute '_jsc'
```

**Expected behavior**

S3A credentials should be injected at session-builder time (before the `SparkContext` starts) so they are part of the initial `Configuration` and no `FileSystem` cache race is possible. The public API for this is `SparkSession.builder.config("spark.hadoop.fs.s3a.access.key", ...)`.

`SparkTask.pre_run` already accepts arbitrary Spark properties via `_SPARK_PROPERTIES`. The fix is to have `pre_run` read `AWS_*` env vars and inject the `spark.hadoop.fs.s3a.*` keys before calling `getOrCreate()`, and remove the `_jsc` path from `io.py` entirely.

**Affected file**

`python/michelangelo/uniflow/plugins/spark/io.py`, line 45:
```python
hadoop_conf = spark.sparkContext._jsc.hadoopConfiguration()
```

**Additional context**

- Introduced in PR #1285 (lazy S3A init refactor).
- The `_jsc` attribute is a CPython implementation detail of the classic PySpark SparkContext; it is absent in Spark Connect and not present in the public PySpark API docs.
- Related: `preprocess.py` line 83 also uses `_jdf.schema().treeString()` (a separate private bridge) — tracked separately.
